package partials

import (
	c "app/components"
	"app/forms"
	"bytes"
	"fmt"
	"log"
	"math/rand"
	"strconv"
	"strings"

	"github.com/go-echarts/go-echarts/v2/charts"
	"github.com/go-echarts/go-echarts/v2/opts"
	"github.com/go-echarts/go-echarts/v2/render"
	. "maragu.dev/gomponents"
	hx "maragu.dev/gomponents-htmx"
	. "maragu.dev/gomponents/html"
)

func SavingsForm(f *forms.SavingsForm) Node {
	return Form(
		hx.Post("/savings-form-partial"),
		hx.Swap("morph"),
		ID("savings-form-partial"),
		Group{
			RenderFields(f),
			RenderResult(f),
		},
	)
}

func RenderFields(f *forms.SavingsForm) Node {
	return Div(
		Class("m-auto max-w-[1600px]"),
		Div(
			Class("mx-10 my-5 text-xl font-bold"),
			Text("Input the information below and instantly see the value created for your company:"),
			A(Class("text-sm underline text-blue-500 float-right ml-1"), Href("/"), Text("Reset")),
		),
		Div(
			Class("grid grid-cols-1 lg:grid-cols-2 gap-x-14 gap-y-7 mx-14 my-5"),
			Div(
				Class("order-1 lg:order-1"),
				InputAndLabel(
					LabelElem("NumOffices", Text("Number of offices")),
					c.InputInt(
						f.NumOffices,
						c.InputOpts{},
						hx.Post("/savings-form-partial"),
						hx.Trigger("input changed delay:500"),
						hx.Target("#savings-form-partial"),
						hx.Swap("morph"),
					),
				),
			),
			Div(
				Class("order-2 lg:order-3"),
				InputAndLabel(
					LabelElem("Volume", Text("Processed $ Volume per month")),
					c.InputInt(
						f.Volume,
						c.InputOpts{Prefix: "$"},
						hx.Post("/savings-form-partial"),
						hx.Trigger("input changed delay:500"),
						hx.Target("#savings-form-partial"),
						hx.Swap("morph"),
					),
				),
			),
			Div(
				Class("order-3 lg:order-5"),
				InputAndLabel(
					LabelElem("AvgStatements", Text("Average total number of patient statements per month")),
					c.InputInt(
						f.AvgStatements,
						c.InputOpts{},
						hx.Post("/savings-form-partial"),
						hx.Trigger("input changed delay:500"),
						hx.Target("#savings-form-partial"),
						hx.Swap("morph"),
					),
				),
			),
			Div(
				Class("order-4 lg:order-7"),
				InputAndLabel(
					LabelElem(
						"AvgPerStatement",
						Text("Average amount per patient statement "),
						c.PopoverComponent(
							"AvgPerStatementPopover",
							c.Icon("info", "16", "16", "inline"),
							Text("Calculated but editable: processed $ volume*35% generated by statements / # statements"),
						),
					),
					c.InputInt(
						f.AvgPerStatement,
						c.InputOpts{Prefix: "$"},
						hx.Post("/savings-form-partial"),
						hx.Trigger("input changed delay:500"),
						hx.Target("#savings-form-partial"),
						hx.Swap("morph"),
					),
				),
			),
			Div(
				Class("order-5 lg:order-2"),
				InputAndLabel(
					LabelElem(
						"TimeBilling",
						Text("Time spent managing billing (hours per week/per office) "),
						c.PopoverComponent(
							"TimeBillingPopover",
							c.Icon("info", "16", "16", "inline"),
							Text("Customer interview average of 20 hours per week/office"),
						),
					),
					c.InputInt(
						f.TimeBilling,
						c.InputOpts{},
						hx.Post("/savings-form-partial"),
						hx.Trigger("input changed delay:500"),
						hx.Target("#savings-form-partial"),
						hx.Swap("morph"),
					),
				),
			),
			Div(
				Class("order-6 lg:order-4"),
				InputAndLabel(
					LabelElem(
						"TimeCollecting",
						Text("Time spent on payment collection and posting (hours per week/per office) "),
						c.PopoverComponent(
							"TimeCollectingPopover",
							c.Icon("info", "16", "16", "inline"),
							Text("Customer interview average of 10 hours per week/office"),
						),
					),
					c.InputInt(
						f.TimeCollecting,
						c.InputOpts{},
						hx.Post("/savings-form-partial"),
						hx.Trigger("input changed delay:500"),
						hx.Target("#savings-form-partial"),
						hx.Swap("morph"),
					),
				),
			),
			Div(
				Class("order-7 lg:order-6"),
				InputAndLabel(
					LabelElem(
						"TimeTeconciling",
						Text("Time spent on payment reconciliation (hours per week/per office) "),
						c.PopoverComponent(
							"TimeReconcilingPopover",
							c.Icon("info", "16", "16", "inline"),
							Text("Customer interview average of 10 hours per week/office"),
						),
					),
					c.InputInt(
						f.TimeReconciling,
						c.InputOpts{},
						hx.Post("/savings-form-partial"),
						hx.Trigger("input changed delay:500"),
						hx.Target("#savings-form-partial"),
						hx.Swap("morph"),
					),
				),
			),
			Div(
				Class("order-8 lg:order-8"),
				InputAndLabel(
					LabelElem("TimeProcessing",
						Text("Time spent processing manual refunds (hours per week/per office) "),
						c.PopoverComponent(
							"TimeProcessingPopover",
							c.Icon("info", "16", "16", "inline"),
							Text("Practices interviewed range 1-2 hrs per week/office"),
						),
					),
					c.InputInt(
						f.TimeProcessing,
						c.InputOpts{},
						hx.Post("/savings-form-partial"),
						hx.Trigger("input changed delay:500"),
						hx.Target("#savings-form-partial"),
						hx.Swap("morph"),
					),
				),
			),
		),
		// Div(
		// 	Class("text-center"),
		// 	c.Btn(c.BtnOpts{Type: "submit"},
		// 		Text("submit"),
		// 	),
		// ),
	)
}

func RenderResult(f *forms.SavingsForm) Node {
	return Div(
		Class("bg-neutral-100"),
		Div(
			Class("py-5 px-5 m-auto max-w-[1600px] 2xl:grid 2xl:grid-cols-2"),
			Div(
				Class("mx-10 my-5"),
				Div(
					Class("my-5 text-xl font-normal"),
					Text("How Practice Management Bridge Can Help You"),
				),
				Div(
					Class("mb-2 text-lg font-bold"),
					Div(
						Class("inline-block w-3.5 h-3.5 mr-2 bg-blue-500"),
					),
					Text("Improve Operational Efficiency"),
				),
				Ul(
					Li(
						Class("flex"),
						Div(
							Class("flex-none mr-1 -mt-1"),
							c.PopoverComponent(
								"AvgPerStatementPopover",
								c.Icon("info", "16", "16", "inline-block"),
								Text("Calculated but editable: processed $ volume*35% generated by statements / # statements"),
							),
						),
						Div(
							Class("flex-grow"),
							Text("Reduce time spent managing billing by"),
							Text(percentFromDecimal(f.PercentSavedBilling)),
							Text("%"),
						),
						Div(Class("flex-none ml-2"), Text("$"), TextInt(f.BillingSavings())),
					),
					Li(
						Class("flex"),
						Div(
							Class("flex-none mr-1 -mt-1"),
							c.PopoverComponent(
								"AvgPerStatementPopover",
								c.Icon("info", "16", "16", "inline-block"),
								Text("Calculated but editable: processed $ volume*35% generated by statements / # statements"),
							),
						),
						Div(
							Class("flex-grow"),
							Text("Reduce time spent on payment collection and posting by "),
							Text(percentFromDecimal(f.PercentSavedCollecting)),
							Text("%"),
						),
						Div(Class("flex-none ml-2"), Text("$"), TextInt(f.CollectionSavings())),
					),
					Li(
						Class("flex"),
						Div(
							Class("flex-none mr-1 -mt-1"),
							c.PopoverComponent(
								"AvgPerStatementPopover",
								c.Icon("info", "16", "16", "inline-block"),
								Text("Calculated but editable: processed $ volume*35% generated by statements / # statements"),
							),
						),
						Div(
							Class("flex-grow"),
							Text("Reduce time spent on payment reconciliation by "),
							Text(percentFromDecimal(f.PercentSavedReconciling)),
							Text("%"),
						),
						Div(Class("flex-none ml-2"), Text("$"), TextInt(f.ReconciliationSavings())),
					),
					Li(
						Class("flex"),
						Div(
							Class("flex-none mr-1 -mt-1"),
							c.PopoverComponent(
								"AvgPerStatementPopover",
								c.Icon("info", "16", "16", "inline-block"),
								Text("Calculated but editable: processed $ volume*35% generated by statements / # statements"),
							),
						),
						Div(
							Class("flex-grow"),
							Text("Reduce time spent processing manual refunds and mailing checks by "),
							Text(percentFromDecimal(f.PercentSavedProcessing)),
							Text("%"),
						),
						Div(Class("flex-none ml-2"), Text("$"), TextInt(f.ProcessingSavings())),
					),
				),
				Div(
					Class("mb-2 mt-4 text-lg font-bold"),
					Div(
						Class("inline-block w-3.5 h-3.5 mr-2 bg-orange-400"),
					),
					Text("Increase Collections"),
				),
				Ul(
					Li(
						Class("flex"),
						Div(
							Class("flex-none mr-1 -mt-1"),
							c.PopoverComponent(
								"AvgPerStatementPopover",
								c.Icon("info", "16", "16", "inline-block"),
								Text("Calculated but editable: processed $ volume*35% generated by statements / # statements"),
							),
						),
						Div(
							Class("flex-grow"),
							Text("Increase patient payment collection rate by 10"),
							Text("%"),
						),
						Div(Class("flex-none ml-2"), Text("$"), TextInt(f.ExtraCollected())),
					),
				),
				Ul(
					Li(
						Class("flex font-bold mt-2"),
						Div(Class("flex-none pt-2")),
						Div(
							Class("flex-grow pt-2"),
							Text("TOTAL VALUE OVER 3 YEARS"),
							Text("%"),
						),
						Div(Class("flex-none ml-2 border-t pt-2"), Text("$"), TextInt(f.TotalValue())),
					),
				),
			),
			Div(
				Class("mx-10 my-5"),
				ID(randID()),
				Div(
					Class("my-5 text-xl font-normal flex"),
					Div(
						Class("flex-1"),
						Text("Overall 3-year value created:"),
					),
					Div(
						Class("flex-none"),
						Text("$"),
						TextInt(f.TotalValue()),
					),
				),
				Div(
					Class("my-5 text-sm font-normal flex"),
					Div(
						Class("flex-1"),
						Text("Monthly cost of waiting (value forfeited per month):"),
					),
					Div(
						Class("flex-none"),
						Text("$"),
						TextInt(f.MonthlyValue()),
					),
				),
				Raw(chart(f)),
				Div(
					Class("text-center text-2xl mb-2 font-bold"),
					Text("Start saving now. Fill out the form below..."),
				),
				Div(
					Class("mb-4 grid grid-cols-2 gap-2 text-white bg-neutral-200 border border-neutral-400 p-5 rounded-md"),
					c.InputString(
						f.FirstName,
						c.InputOpts{Label: "First Name"},
					),
					c.InputString(
						f.LastName,
						c.InputOpts{Label: "Last Name"},
					),
					c.InputString(
						f.Email,
						c.InputOpts{Label: "Email"},
					),
					c.InputString(
						f.Phone,
						c.InputOpts{Label: "Phone"},
					),
				),
				Div(
					Class("text-center"),
					Button(
						Name("button"),
						Value("clicked"),
						Type("submit"),
						Class("cursor-pointer text-center font-bold text-white shadow-md text-xl bg-orange-400 rounded-md px-3 py-2"),
						Text("Contact Us"),
					),
				),
			),
		),
		Div(
			Class("bg-neutral-700"),
			Div(
				Class("p-5 m-auto max-w-[1600px] text-white text-sm font-light"),
				Text(`
					The Return-on-Investment (ROI) and other financial calculations performed by this tool are based on data provided by Practice Management Bridge® customers, and various assumptions, and produce estimates only. The actual ROI realized by customers may vary from the estimates provided. This tool is being offered to assist customers with evaluating their health care payments solutions; however, Practice Management Bridge and Hobson & Company (the firm that created the tool) are not responsible for the accuracy of any estimates.
				`),
			),
		),
	)
}

func randID() string {
	return strconv.FormatInt(rand.Int63(), 10)
}

func TextInt(i int) Node {
	return Text(forms.FmtInt(i))
}

func LabelElem(labelFor string, elements ...Node) Node {
	return Label(
		For(labelFor),
		Class("block text-sm/7 font-light text-gray-900"),
		Group(elements),
	)
}

func InputAndLabel(label Node, input Node) Node {
	return Div(
		Class("grid grid-cols-[55%_45%] gap-6 items-top"),
		label,
		Div(input),
	)
}

func percentFromDecimal(n float64) string {
	return fmt.Sprintf(" %s", strconv.Itoa(int(n*100)))
}

func chart(sf *forms.SavingsForm) string {
	pie := charts.NewPie()

	pieData := []opts.PieData{
		{
			Name:  "Improve Operational Efficiency",
			Value: sf.ImproveOpSavings(),
			ItemStyle: &opts.ItemStyle{
				Color: "#2b7fff",
			},
		},
		{
			Name:  "Increase Collections",
			Value: sf.ExtraCollected(),
			ItemStyle: &opts.ItemStyle{
				Color: "#ff8904",
			},
		},
	}

	initOpts := opts.Initialization{
		Width:  "350px", // Chart width
		Height: "350px", // Chart height
	}

	pie.SetGlobalOptions(charts.WithInitializationOpts(initOpts))

	pie.AddSeries("", pieData).SetSeriesOptions(charts.WithAnimationOpts(opts.Animation{Animation: opts.Bool(false)}))

	return renderToHtmlString(pie)
}

func renderToHtmlString(c any) string {
	var buf bytes.Buffer
	r := c.(render.Renderer)
	err := r.Render(&buf)
	if err != nil {
		log.Printf("Failed to render chart: %s", err)
		return ""
	}

	return strings.Replace(buf.String(), `class="container"`, "", 1)
}
