package assets

// Code generated by go:generate; DO NOT EDIT.

var assetMap = map[string]string{
	"/styles/app.css":"/styles/app-5d5b70e4c76bdf3020b2cd75c0d2bb0b.css",
	"/favicon.ico":"/favicon-d41d8cd98f00b204e9800998ecf8427e.ico",
	"/images/logo.png":"/images/logo-b8e5f2fdc25416b4c9140aee0c2dc5ac.png",
	"/scripts/app.js":"/scripts/app-d41d8cd98f00b204e9800998ecf8427e.js",
	"/scripts/htmx.js":"/scripts/htmx-892c198f5088ca057adc64955f0bfde8.js",
	"/scripts/idiomorph.js":"/scripts/idiomorph-2569dd7e85436ceb0c9a6e7fbc3e30ee.js",
	"/scripts/tailwind-elements.js":"/scripts/tailwind-elements-63cef7b7c94a840dfcb7d16ef4487dad.js",
}

	func Path(path string) string {
		if hash, ok := assetMap[path]; ok {
			return hash
		}
		return "/" + path
	}
	
