package assets

// Code generated by go:generate; DO NOT EDIT.

var assetMap = map[string]string{
	"/favicon.ico":"/favicon-d41d8cd98f00b204e9800998ecf8427e.ico",
	"/images/logo.png":"/images/logo-b8e5f2fdc25416b4c9140aee0c2dc5ac.png",
	"/scripts/app.js":"/scripts/app-d41d8cd98f00b204e9800998ecf8427e.js",
	"/scripts/htmx.js":"/scripts/htmx-892c198f5088ca057adc64955f0bfde8.js",
	"/styles/app.css":"/styles/app-19aec9509670621ebe95cec46782e7f5.css",
}

	func Path(path string) string {
		if hash, ok := assetMap[path]; ok {
			return hash
		}
		return "/" + path
	}
	
